# Generated by Django 2.2.17 on 2021-04-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favouriteShow',
        ),
    ]
