# Generated by Django 2.2.17 on 2021-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0002_remove_userprofile_favouriteshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='showTitle',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
