# Generated by Django 2.2.17 on 2021-04-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0003_remove_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favouriteShow',
            field=models.IntegerField(default=0),
        ),
    ]
