# Generated by Django 2.2.17 on 2021-04-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0004_userprofile_favouriteshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favouriteShow',
            field=models.IntegerField(default=None),
        ),
    ]
