# Generated by Django 2.2.17 on 2021-04-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0007_auto_20210405_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favouriteShow',
        ),
    ]
