# Generated by Django 2.2.17 on 2021-04-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0008_remove_userprofile_favouriteshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favouriteShow',
            field=models.IntegerField(default=None),
        ),
    ]
