# Generated by Django 2.2.17 on 2021-04-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0009_userprofile_favouriteshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favouriteShow',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('review', models.CharField(blank=True, max_length=10000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyTvList.UserProfile')),
            ],
        ),
    ]
