# Generated by Django 2.2.17 on 2021-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTvList', '0010_auto_20210405_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favouriteShow',
            field=models.IntegerField(default=None),
        ),
    ]
